# Generated by Django 2.1.4 on 2018-12-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostName',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.URLField()),
                ('ctime', models.DateField()),
                ('ssl_time', models.DateField()),
                ('ssl_otime', models.DateField()),
                ('ssl', models.FileField(upload_to='')),
            ],
        ),
    ]
